name: ExplodePlayer
version: ${project.version}
main: net.bghddev.explode.explodeplayer.ExplodePlayer
authors: [BGHDDevelopment]
description: Players explode every minute.
website: https://youtube.com/BGHDDevelopment
